runtime: nodejs
vm: true
api_version: 1

# f1-micro target
resources:
  cpu: .5
  memory_gb: .6
  disk_size_gb: 10

# can't use min instance 0 with auto scaling...
manual_scaling:
  instances: 1

# Temporary workaround for a Cloud SDK bug.
# Ensures that node_modules directory and any .log files are not uploaded (the
# other entries are the default values for skip_files). This will skip any Unix
# hidden files (such as the .git directory)
skip_files:
 - ^(.*/)?#.*#$
 - ^(.*/)?.*~$
 - ^(.*/)?.*\.py[co]$
 - ^(.*/)?.*/RCS/.*$
 - ^(.*/)?\..*$
 - ^(.*/)?.*/node_modules/.*$
 - ^(.*/)?.*\.log$
